export type PaletteColor = { name: string; hex: string };

export const SEASON_PALETTE_REFERENCE: Record<string, PaletteColor[]> = {
  "light-spring": [
    { name: "Ivory",            hex: "#FFF3E0" },
    { name: "Warm Peach",       hex: "#FDBCB4" },
    { name: "Apricot",          hex: "#F4A96A" },
    { name: "Powder Pink",      hex: "#FFD1DC" },
    { name: "Warm Coral",       hex: "#F4826A" },
    { name: "Butter Yellow",    hex: "#FFF0A0" },
    { name: "Honey",            hex: "#FFBF47" },
    { name: "Warm Mint",        hex: "#B5EAD7" },
    { name: "Sky Blue",         hex: "#87CEEB" },
    { name: "Clear Turquoise",  hex: "#7DDDE2" },
    { name: "Camel",            hex: "#D4A76A" },
    { name: "Warm Champagne",   hex: "#F5E6C8" },
    { name: "Warm Beige",       hex: "#D4B896" },
    { name: "Light Warm Brown", hex: "#C4956A" },
    { name: "Salmon",           hex: "#FA8072" },
    { name: "Soft Gold",        hex: "#ECC98A" },
  ],

  "true-spring": [
    { name: "Warm Coral",       hex: "#F4784A" },
    { name: "Clear Orange",     hex: "#FF8C42" },
    { name: "Marigold",         hex: "#F5C518" },
    { name: "Turquoise",        hex: "#40C5B5" },
    { name: "Clear Aqua",       hex: "#00BCD4" },
    { name: "Warm Olive",       hex: "#8A9A3A" },
    { name: "Caramel",          hex: "#C07A3A" },
    { name: "Ivory",            hex: "#FFFBF0" },
    { name: "Watermelon",       hex: "#FC5C65" },
    { name: "Warm Navy",        hex: "#1C3F5E" },
    { name: "Warm Green",       hex: "#5A9E4A" },
    { name: "Apricot",          hex: "#FBCEB1" },
    { name: "Tomato Red",       hex: "#D94F4F" },
    { name: "Cobalt Blue",      hex: "#0047AB" },
    { name: "Golden Yellow",    hex: "#F5C518" },
    { name: "Peach",            hex: "#FFBB99" },
  ],

  "bright-spring": [
    { name: "Hot Coral",        hex: "#FF6B5B" },
    { name: "Bright Yellow",    hex: "#FFC72C" },
    { name: "Vivid Turquoise",  hex: "#00C8C8" },
    { name: "Vivid Green",      hex: "#22B573" },
    { name: "Royal Blue",       hex: "#2E52A3" },
    { name: "Bright Red",       hex: "#E8303A" },
    { name: "Bright Pink",      hex: "#FF84A8" },
    { name: "Clear Navy",       hex: "#003F8C" },
    { name: "Ivory",            hex: "#FFFFF5" },
    { name: "Hot Orange",       hex: "#FF6F00" },
    { name: "Bright Aqua",      hex: "#00C8B4" },
    { name: "Golden Yellow",    hex: "#FFD700" },
    { name: "True Black",       hex: "#1A1A1A" },
    { name: "Vivid Purple",     hex: "#7B2FD8" },
    { name: "Warm Magenta",     hex: "#D82878" },
    { name: "Clear Lime",       hex: "#8BC34A" },
  ],

  "light-summer": [
    { name: "Powder Blue",      hex: "#B0C4DE" },
    { name: "Soft Lavender",    hex: "#C8A8C8" },
    { name: "Rose Water",       hex: "#F0D0D5" },
    { name: "Dusty Rose",       hex: "#D4A5A5" },
    { name: "Dove Grey",        hex: "#A8A8B5" },
    { name: "Sage",             hex: "#8FA89A" },
    { name: "Light Denim",      hex: "#7C9CB8" },
    { name: "Soft White",       hex: "#F5F0F0" },
    { name: "Soft Lilac",       hex: "#C9B8D8" },
    { name: "Periwinkle",       hex: "#9FA8DA" },
    { name: "Muted Rose",       hex: "#C49898" },
    { name: "Cool Mint",        hex: "#A8D8C8" },
    { name: "Rose Taupe",       hex: "#9E8080" },
    { name: "Soft Pink",        hex: "#E8B4B8" },
    { name: "Steel Blue",       hex: "#7B9CB8" },
    { name: "Muted Mauve",      hex: "#B898B0" },
  ],

  "true-summer": [
    { name: "Rose Mauve",       hex: "#C08080" },
    { name: "Soft Navy",        hex: "#4A6FA5" },
    { name: "Lavender Blue",    hex: "#7B83B8" },
    { name: "Cool Pink",        hex: "#D4809C" },
    { name: "Sage Green",       hex: "#7A9E7E" },
    { name: "Steel Blue",       hex: "#5B7FA6" },
    { name: "Dusty Rose",       hex: "#C49898" },
    { name: "Periwinkle",       hex: "#8F9FD0" },
    { name: "Muted Teal",       hex: "#6B9E9A" },
    { name: "Grey Blue",        hex: "#8898B0" },
    { name: "Cool Raspberry",   hex: "#A84060" },
    { name: "Dusty Blue",       hex: "#8598B0" },
    { name: "Cool Red",         hex: "#B83048" },
    { name: "Soft Plum",        hex: "#907080" },
    { name: "Muted Lavender",   hex: "#A898C0" },
    { name: "Greige",           hex: "#C0B8B0" },
  ],

  "soft-summer": [
    { name: "Dusty Mauve",      hex: "#C0A0A8" },
    { name: "Muted Navy",       hex: "#5A6E8C" },
    { name: "Sage",             hex: "#8A9E8E" },
    { name: "Warm Grey",        hex: "#A8A0A0" },
    { name: "Rose Brown",       hex: "#A88080" },
    { name: "Dusty Blue",       hex: "#8598B0" },
    { name: "Muted Lavender",   hex: "#A898C0" },
    { name: "Greige",           hex: "#C0B8B0" },
    { name: "Dusty Teal",       hex: "#7A9898" },
    { name: "Soft Plum",        hex: "#907080" },
    { name: "Cocoa",            hex: "#A87A70" },
    { name: "Dusty Pink",       hex: "#C8A0A8" },
    { name: "Muted Blush",      hex: "#D0B0B0" },
    { name: "Stone Blue",       hex: "#8090A0" },
    { name: "Dusty Olive",      hex: "#9A9E80" },
    { name: "Muted Burgundy",   hex: "#906070" },
  ],

  "soft-autumn": [
    { name: "Warm Taupe",       hex: "#B8987A" },
    { name: "Sage Green",       hex: "#8A9E78" },
    { name: "Dusty Coral",      hex: "#D4907A" },
    { name: "Warm Camel",       hex: "#C4A278" },
    { name: "Soft Teal",        hex: "#7A9E98" },
    { name: "Warm Ivory",       hex: "#F5E8D8" },
    { name: "Dusty Gold",       hex: "#C0A050" },
    { name: "Warm Olive",       hex: "#8A9060" },
    { name: "Soft Brown",       hex: "#A07858" },
    { name: "Muted Peach",      hex: "#D4A898" },
    { name: "Warm Grey",        hex: "#B0A898" },
    { name: "Dusty Rose",       hex: "#C4958A" },
    { name: "Warm Sage",        hex: "#9AA870" },
    { name: "Wheat",            hex: "#D4C0A0" },
    { name: "Warm Stone",       hex: "#C0B0A0" },
    { name: "Muted Salmon",     hex: "#D0988A" },
  ],

  "true-autumn": [
    { name: "Terracotta",       hex: "#C4622D" },
    { name: "Camel",            hex: "#C19A6B" },
    { name: "Warm Olive",       hex: "#6B7C4B" },
    { name: "Rust",             hex: "#9B4E2E" },
    { name: "Dark Gold",        hex: "#B8860B" },
    { name: "Chocolate Brown",  hex: "#7A4A30" },
    { name: "Forest Green",     hex: "#4A6B3A" },
    { name: "Burnt Orange",     hex: "#C05A2A" },
    { name: "Teal",             hex: "#2E7A7A" },
    { name: "Warm Red",         hex: "#A03028" },
    { name: "Pumpkin",          hex: "#D4642A" },
    { name: "Mustard",          hex: "#C8A820" },
    { name: "Bronze",           hex: "#8A6030" },
    { name: "Warm Brown",       hex: "#8B5E3C" },
    { name: "Moss",             hex: "#7D8C4A" },
    { name: "Cream",            hex: "#F5E8D0" },
  ],

  "dark-autumn": [
    { name: "Deep Terracotta",  hex: "#9B4020" },
    { name: "Dark Olive",       hex: "#5A6830" },
    { name: "Burgundy",         hex: "#6B2030" },
    { name: "Dark Camel",       hex: "#A07840" },
    { name: "Deep Teal",        hex: "#1E5A5A" },
    { name: "Chocolate",        hex: "#4A2818" },
    { name: "Dark Forest",      hex: "#2E4A2E" },
    { name: "Warm Gold",        hex: "#A08030" },
    { name: "Deep Rust",        hex: "#8B3020" },
    { name: "Dark Plum",        hex: "#4A2840" },
    { name: "Mahogany",         hex: "#5A2818" },
    { name: "Deep Bronze",      hex: "#7A5020" },
    { name: "Burnt Sienna",     hex: "#8B4020" },
    { name: "Dark Moss",        hex: "#404A20" },
    { name: "Spice",            hex: "#8A3820" },
    { name: "Warm Cream",       hex: "#E8D8C0" },
  ],

  "dark-winter": [
    { name: "Deep Burgundy",    hex: "#5A1020" },
    { name: "Deep Navy",        hex: "#0A1428" },
    { name: "Dark Forest",      hex: "#1A3A28" },
    { name: "Charcoal",         hex: "#2A2A2A" },
    { name: "Deep Purple",      hex: "#3A1858" },
    { name: "Dark Teal",        hex: "#0A3040" },
    { name: "Deep Plum",        hex: "#3A0840" },
    { name: "Dark Wine",        hex: "#4A0018" },
    { name: "True Black",       hex: "#0A0A0A" },
    { name: "Dark Emerald",     hex: "#0A3828" },
    { name: "Eggplant",         hex: "#380840" },
    { name: "Dark Pine",        hex: "#0A2818" },
    { name: "Oxblood",          hex: "#480818" },
    { name: "Dark Cobalt",      hex: "#0A1878" },
    { name: "Smoke",            hex: "#3A3A4A" },
    { name: "Cool Ivory",       hex: "#E8E8F0" },
  ],

  "true-winter": [
    { name: "True Black",       hex: "#0A0A0A" },
    { name: "Pure White",       hex: "#F5F5F8" },
    { name: "Cool Red",         hex: "#C82030" },
    { name: "Royal Blue",       hex: "#0038A8" },
    { name: "Deep Purple",      hex: "#4A1880" },
    { name: "Icy Blue",         hex: "#A0B8D0" },
    { name: "True Navy",        hex: "#0A1844" },
    { name: "Cobalt",           hex: "#0038A8" },
    { name: "Cool Pink",        hex: "#D84878" },
    { name: "Charcoal",         hex: "#2A2A38" },
    { name: "Emerald",          hex: "#008050" },
    { name: "Bright Purple",    hex: "#5018A8" },
    { name: "Icy Lavender",     hex: "#C8C0E0" },
    { name: "Cool Fuchsia",     hex: "#D020A0" },
    { name: "Deep Teal",        hex: "#006878" },
    { name: "Icy Pink",         hex: "#E0C0D0" },
  ],

  "bright-winter": [
    { name: "Pure White",       hex: "#F8F8F8" },
    { name: "True Black",       hex: "#0A0A0A" },
    { name: "Vivid Blue",       hex: "#0048C8" },
    { name: "Bright Red",       hex: "#D82028" },
    { name: "Emerald",          hex: "#008858" },
    { name: "Magenta",          hex: "#C82878" },
    { name: "Royal Blue",       hex: "#2038A8" },
    { name: "Bright Purple",    hex: "#5820A0" },
    { name: "Vivid Teal",       hex: "#007878" },
    { name: "Hot Pink",         hex: "#D83878" },
    { name: "Cobalt",           hex: "#0038C8" },
    { name: "Vivid Green",      hex: "#00A850" },
    { name: "Electric Blue",    hex: "#0068E8" },
    { name: "Bright Fuchsia",   hex: "#E028A8" },
    { name: "Icy White",        hex: "#F0F4F8" },
    { name: "Sharp Yellow",     hex: "#FFE000" },
  ],
};
